# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fe14df7ab8ad188443de873adfa31f8c555512b31c2d13c026861dc9ef9b149283738185196062a3a4a28a75577b312918847e6cb7930c2fc0dbf0f7bfc4c6c9

test:
  secret_key_base: e413bc30c6024894a50b7e2fbcfcd96e40cf7df5e2b5f15b8eb5145750b969fa1bbbcc474072686a7387c05e21334c0665bddaa4ab99c3a5f5a8f731bd7c99bf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
